### ISSUE TITLE
Failure to start with users with no home directory and/or nologin

### ISSUE THREAD

**Issue by Kreeblah** [aleksasiriski/autoscan#12]
Since Cloudbox doesn't seem to be too active any more and your fork is more recently maintained, I guess I should post this here, too.

When `autoscan` runs under a user with either nologin or no home directory (I'm not sure which of the two is triggering it, to be honest), it fails with the following error:

```
panic: mkdirall: mkdir /nonexistent: permission denied

goroutine 1 [running]:
main.defaultConfigDirectory({0xace36e, 0x8}, {0xacf1e7, 0xa})
	github.com/cloudbox/autoscan/cmd/autoscan/config.go:27 +0x1d9
main.main()
	github.com/cloudbox/autoscan/cmd/autoscan/main.go:120 +0x2f4
```

This is even true when passing the `--config`, `--database`, and `--log` flags, so it seems to be hitting https://github.com/Cloudbox/autoscan/blob/master/cmd/autoscan/config.go#L26 and attempting to create directories even though it doesn't need to.  Since `os.UserConfigDir()` is returning something invalid but not an actual error (`err` is apparently still `nil`), that causes `autoscan` to panic on startup when running on a system where it has its own user to run as a service, but without login permissions or a home directory, as is the case on FreeBSD.

**Comment by aleksasiriski** [comment]
I'll be recreating this package soon with better libs for certain features and will switch the Dockerfile to distroless. I'll look out to test this usecase of yours

**Comment by aleksasiriski** [comment]
I didn't find the time to fix this error, so if you found the solution PRs are welcome.
